name: Test CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ 1.8, 11, 13, '14-ea', '15-ea' ]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - uses: LouisBrunner/checks-action@v0.1.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job }}
          output:
            summary: ${{ steps.test.outputs.summary }}
            text_description: ${{ steps.test.outputs.description }}
